! EXAMPLE-01: FREQUENCY ESTIMATION (SIGNAL WITH ONE HARMONIC)
PROGRAM EXAMPLE

  USE SIGNAL

  IMPLICIT NONE

  INTEGER(IK), PARAMETER           :: LENGTH = 2_IK**10_IK  ! INPUT SIGNAL LENGTH
  INTEGER(IK)                      :: FLAG                  ! COMPLEX FLAG (0/1)
  REAL(RK)                         :: RANGE_MIN             ! (MIN) FREQUENCY RANGE
  REAL(RK)                         :: RANGE_MAX             ! (MAX) FREQUENCY RANGE
  INTEGER(IK)                      :: PEAK                  ! FOURIE SPECTRA PEAK ID
  INTEGER(IK)                      :: METHOD                ! FREQUENCY ESTIMATION METHOD
  INTEGER(IK)                      :: ORDER                 ! COSINE WINDOW ORDER
  REAL(RK), DIMENSION(LENGTH)      :: WINDOW                ! COSINE WINDOW DATA
  REAL(RK)                         :: TOTAL                 ! SUM OF WINDOW ELEMENTS
  REAL(RK)                         :: FREQUENCY             ! EXACT SIGNAL FREQUENCY
  REAL(RK), DIMENSION(LENGTH)      :: SIGNAL_R, SIGNAL_I    ! SIGNAL REAL AND COMPLEX PARTS
  REAL(RK), DIMENSION(2_IK*LENGTH) :: SIGNAL                ! INPUT SIGNAL, [..., SR_I, SI_I, ...]
  REAL(RK)                         :: RESULT                ! FREQUENCY ESTIMATION

  INTEGER(IK)                      :: I

  ! SET COMPLEX FLAG (0/1 FOR REAL/COMPLEX SIGNAL)
  ! FLAG IS USED BY FREQUENCY_ FUNCTION
  ! FOR REAL SIGNALS (FLAG = 0) 1ST HALF OF FOURIE AMPLITUDE SPETRUM IS USED FOR FREQUENCY ESTIMATION
  ! FREQUENCY RESOLUTION IS [0.0,0.5]
  ! FOR COMPLEX SIGNALS (FLAG = 1) FULL FOURIE AMPLITUDE SPECTRA IS USED FOR FREQUENCY ESTIMATION
  ! FREQUENCY RESOLUTION IS [0.0,1.0]
  FLAG = 1_IK

  ! SET FREQUENCY RANGE (0.0 <= RANGE_MIN <= RANGE_MAX <= 1.0)
  ! FREQUENCY RANGE CAN BE USED TO TARGET SELECTED RANGE OF FREQUENCIES
  ! MAX RANGE SHOULD MATCH <FLAG>, I.E. SHOULD BE LESS OR EQUAL TO LARGEST FREQUENCY DEFINED BY <FLAG>
  RANGE_MIN = 0.0_RK
  RANGE_MAX = 1.0_RK/(2.0_RK-REAL(FLAG, RK))

  ! SET SIGNAL EXACT FREQUENCY, REAL AND IMAGINARY PARTS
  FREQUENCY = 0.2143658791_RK
  DO I = 1_IK, LENGTH, 1_IK
    SIGNAL_R(I) = +COS(TWO_PI*FREQUENCY*REAL(I, RK))
    SIGNAL_I(I) = -SIN(TWO_PI*FREQUENCY*REAL(I, RK))
  END DO

  ! ADD CONSTANT COMPONENT
  SIGNAL_R = SIGNAL_R + 0.1_RK

  ! FORMAT TEST SIGNAL
  ! SIGNAL_R = [..., SR_I, ...]
  ! SIGNAL_I = [..., SI_I, ...]
  ! SIGNAL = [..., SR_I, SI_I, ...]
  SIGNAL = 0.0_RK
  IF(FLAG == 0_IK) THEN
    CALL CONVERT_(LENGTH, SIGNAL_R, SIGNAL)
  ELSE
    CALL CONVERT_(LENGTH, SIGNAL_R, SIGNAL_I, SIGNAL)
  END IF

  ! SET WINDOW AND WINDOW SUM
  ORDER = 2_IK
  CALL WINDOW_(LENGTH, ORDER, WINDOW)
  TOTAL = SUM(WINDOW)

  ! IF SIGNAL LENGTH IS NOT EQUAL TO POWER OF TWO
  ! SIGNAL CAN BE PADDED WITH ZEROS TO THE NEAREST POWER OF TWO LENGTH
  ! IN THIS EXAMPLE SIGNAL HAS CORRECT LENGTH

  ! ROUND_UP_(LENGTH) RETURNS NEXT POWER OF TWO LENGTH
  WRITE(*, '(1A,1I10)') "LENGTH         : ", LENGTH
  WRITE(*, '(1A,1I10)') "NEXT LENGTH    : ", ROUND_UP_(LENGTH)

  ! ESTIMATE FREQUENCY
  ! SIGNAL SHOULD HAVE POWER OF TWO LENGTH (REAL AND IMAGINARY PART)

  ! PEAK = 0 USES LARGEST FOURIER AMPLITUDE SPECTRA BIN
  ! PEAK = N USES N'TH FOURIER AMPLITUDE SPECTRA PEAK
  ! FFT IS DEFINED BY __FFT__ DIRECTIVE
  ! FFT_RADIX_TWO_    -- RADIX-TWO FFT (NRF77), THREADSAFE
  ! FFT_RADIX_EIGHT_  -- RADIX-EIGHT FFT (TAKUYA OOURA), DEFAULT, THREADSAFE
  ! FFT_EXTERNAL_     -- FFTW, NOT THREADSAFE

  WRITE(*, '(1A,1I10)') "FLAG           : ", FLAG
  WRITE(*, '(1A,1I10)') "ORDER          : ", ORDER

  ! ESTIMATE FREQUENCY (MAXIMUM BIN)
  WRITE(*, '(1A)') "(MAXIMUM BIN)"
  PEAK = 0_IK
  ! FFT MAX BIN OR SELECTED PEAK
  METHOD = FREQUENCY_FFT
  RESULT = FREQUENCY_(FLAG, RANGE_MIN, RANGE_MAX, PEAK, METHOD, LENGTH, LENGTH, TOTAL, WINDOW, SIGNAL)
  WRITE(*, '(1A,2E32.16)') "FFT            : ", RESULT, ABS(RESULT-FREQUENCY)
  ! FFT MAX BIN OR SELECTED PEAK AND ZERO PADDING
  METHOD = FREQUENCY_FFT
  RESULT = FREQUENCY_(FLAG, RANGE_MIN, RANGE_MAX, PEAK, METHOD, LENGTH, 2_IK*LENGTH, TOTAL, WINDOW, SIGNAL)
  WRITE(*, '(1A,2E32.16)') "FFT (PADDED)   : ", RESULT, ABS(RESULT-FREQUENCY)
  ! FFRFT REFINED SPECTRA
  METHOD = FREQUENCY_FFRFT
  RESULT = FREQUENCY_(FLAG, RANGE_MIN, RANGE_MAX, PEAK, METHOD, LENGTH, LENGTH, TOTAL, WINDOW, SIGNAL)
  WRITE(*, '(1A,2E32.16)') "FFRFT          : ", RESULT, ABS(RESULT-FREQUENCY)
  ! PARABOLA INTERPOLATION OF FFRFT REFINED SPECTRA
  METHOD = FREQUENCY_PARABOLA
  RESULT = FREQUENCY_(FLAG, RANGE_MIN, RANGE_MAX, PEAK, METHOD, LENGTH, LENGTH, TOTAL, WINDOW, SIGNAL)
  WRITE(*, '(1A,2E32.16)') "PARABOLA       : ", RESULT, ABS(RESULT-FREQUENCY)
  ! PARABOLA FIT OF FFRFT REFINED SPECTRA
  ! NUMBER OF FIT POINTS IS GIVEN BY <PARABOLA_FIT_LENGTH> PARAMETER
  METHOD = FREQUENCY_PARABOLA_FIT
  RESULT = FREQUENCY_(FLAG, RANGE_MIN, RANGE_MAX, PEAK, METHOD, LENGTH, LENGTH, TOTAL, WINDOW, SIGNAL)
  WRITE(*, '(1A,2E32.16)') "PARABOLA (FIT) : ", RESULT, ABS(RESULT-FREQUENCY)
  ! MAXIMUM SEARCH OF DTFT SPECTRA
  ! SEARCH FUNCTION IS DEFINED BY __SEARCH__ DIRECTIVE
  ! MAXIMUM NUMBER OF ITERATIONS IS CONTROLLED BY <SEARCH_LIMIT> PARAMETER
  ! SEARCH TOLERANCE IS CONTROLLED BY <SEARCH_TOLERANCE> PARAMETER
  METHOD = FREQUENCY_SEARCH
  RESULT = FREQUENCY_(FLAG, RANGE_MIN, RANGE_MAX, PEAK, METHOD, LENGTH, LENGTH, TOTAL, WINDOW, SIGNAL)
  WRITE(*, '(1A,2E32.16)') "SEARCH         : ", RESULT, ABS(RESULT-FREQUENCY)

  ! IF PEAK \= 0, PEAK DETECTION IS USED TO LOCATE SELECTED PEAK
  ! PEAKS ARE SORTED BY __SORT__
  ! SORT_BUBBLE_      -- BUBBLE SORT
  ! SORT_QUICK_       -- QUICK SORT, DEFAULT
  ! ESTIMATE FREQUENCY (1ST PEAK)
  WRITE(*, '(1A)') "(1ST PEAK)"
  PEAK = 1_IK
  METHOD = FREQUENCY_FFT
  RESULT = FREQUENCY_(FLAG, RANGE_MIN, RANGE_MAX, PEAK, METHOD, LENGTH, LENGTH, TOTAL, WINDOW, SIGNAL)
  WRITE(*, '(1A,2E32.16)') "FFT            : ", RESULT, ABS(RESULT-FREQUENCY)
  METHOD = FREQUENCY_FFT
  RESULT = FREQUENCY_(FLAG, RANGE_MIN, RANGE_MAX, PEAK, METHOD, LENGTH, 2_IK*LENGTH, TOTAL, WINDOW, SIGNAL)
  WRITE(*, '(1A,2E32.16)') "FFT (PADDED)   : ", RESULT, ABS(RESULT-FREQUENCY)
  METHOD = FREQUENCY_FFRFT
  RESULT = FREQUENCY_(FLAG, RANGE_MIN, RANGE_MAX, PEAK, METHOD, LENGTH, LENGTH, TOTAL, WINDOW, SIGNAL)
  WRITE(*, '(1A,2E32.16)') "FFRFT          : ", RESULT, ABS(RESULT-FREQUENCY)
  METHOD = FREQUENCY_PARABOLA
  RESULT = FREQUENCY_(FLAG, RANGE_MIN, RANGE_MAX, PEAK, METHOD, LENGTH, LENGTH, TOTAL, WINDOW, SIGNAL)
  WRITE(*, '(1A,2E32.16)') "PARABOLA       : ", RESULT, ABS(RESULT-FREQUENCY)
  METHOD = FREQUENCY_PARABOLA_FIT
  RESULT = FREQUENCY_(FLAG, RANGE_MIN, RANGE_MAX, PEAK, METHOD, LENGTH, LENGTH, TOTAL, WINDOW, SIGNAL)
  WRITE(*, '(1A,2E32.16)') "PARABOLA (FIT) : ", RESULT, ABS(RESULT-FREQUENCY)
  METHOD = FREQUENCY_SEARCH
  RESULT = FREQUENCY_(FLAG, RANGE_MIN, RANGE_MAX, PEAK, METHOD, LENGTH, LENGTH, TOTAL, WINDOW, SIGNAL)
  WRITE(*, '(1A,2E32.16)') "SEARCH         : ", RESULT, ABS(RESULT-FREQUENCY)

END PROGRAM EXAMPLE