! EXAMPLE-04: HARMONIC SIGNAL DECOMPOSITION (LEAST SQUARES)
PROGRAM EXAMPLE

  USE :: SIGNAL

  IMPLICIT NONE

  REAL(RK), PARAMETER :: A0 = 0.35_RK

  REAL(RK), PARAMETER :: F1 = 1.0_RK*0.123456789_RK
  REAL(RK), PARAMETER :: A1 = 1.0_RK
  REAL(RK), PARAMETER :: B1 = 0.5_RK

  REAL(RK), PARAMETER :: F2 = 2.0_RK*0.123456789_RK
  REAL(RK), PARAMETER :: A2 = 0.05_RK
  REAL(RK), PARAMETER :: B2 = 0.01_RK

  REAL(RK), PARAMETER :: F3 = 3.0_RK*0.123456789_RK
  REAL(RK), PARAMETER :: A3 = 0.001_RK
  REAL(RK), PARAMETER :: B3 = 0.005_RK

  INTEGER(IK), PARAMETER :: LENGTH = 256_RK
  REAL(RK), DIMENSION(LENGTH) :: SIGNAL

  INTEGER(IK) :: LIMIT
  REAL(RK) :: MEAN
  REAL(RK), DIMENSION(:), ALLOCATABLE :: FREQUENCY
  REAL(RK), DIMENSION(:), ALLOCATABLE :: COS_AMP
  REAL(RK), DIMENSION(:), ALLOCATABLE :: SIN_AMP
  REAL(RK) :: ERROR

  INTEGER :: I

  SIGNAL = A0
  DO I = 1_IK, LENGTH, 1_IK
    SIGNAL(I) = &
      A1*COS(TWO_PI*F1*REAL(I, RK)) + B1*SIN(TWO_PI*F1*REAL(I, RK)) + &
      A2*COS(TWO_PI*F2*REAL(I, RK)) + B2*SIN(TWO_PI*F2*REAL(I, RK)) + &
      A3*COS(TWO_PI*F3*REAL(I, RK)) + B3*SIN(TWO_PI*F3*REAL(I, RK))
  END DO

  ! FIT (ONE HARMONIC)
  LIMIT = 1_IK
  ALLOCATE(FREQUENCY(LIMIT))
  ALLOCATE(COS_AMP(LIMIT))
  ALLOCATE(SIN_AMP(LIMIT))
  FREQUENCY = [F1,F2]
  CALL FIT_(LENGTH, SIGNAL, LIMIT, FREQUENCY, MEAN, COS_AMP, SIN_AMP, ERROR)
  WRITE(*,*) ERROR
  WRITE(*,*) MEAN
  DO I = 1_IK, LIMIT,1_IK
    WRITE(*,*) COS_AMP(I), SIN_AMP(I)
  END DO
  WRITE(*,*)
  DEALLOCATE(FREQUENCY)
  DEALLOCATE(COS_AMP)
  DEALLOCATE(SIN_AMP)

  ! FIT (TWO HARMONICS)
  LIMIT = 2_IK
  ALLOCATE(FREQUENCY(LIMIT))
  ALLOCATE(COS_AMP(LIMIT))
  ALLOCATE(SIN_AMP(LIMIT))
  FREQUENCY = [F1,F2]
  CALL FIT_(LENGTH, SIGNAL, LIMIT, FREQUENCY, MEAN, COS_AMP, SIN_AMP, ERROR)
  WRITE(*,*) ERROR
  WRITE(*,*) MEAN
  DO I = 1_IK, LIMIT,1_IK
    WRITE(*,*) COS_AMP(I), SIN_AMP(I)
  END DO
  WRITE(*,*)
  DEALLOCATE(FREQUENCY)
  DEALLOCATE(COS_AMP)
  DEALLOCATE(SIN_AMP)

  ! FIT (THREE HARMONICS)
  LIMIT = 3_IK
  ALLOCATE(FREQUENCY(LIMIT))
  ALLOCATE(COS_AMP(LIMIT))
  ALLOCATE(SIN_AMP(LIMIT))
  FREQUENCY = [F1,F2,F3]
  CALL FIT_(LENGTH, SIGNAL, LIMIT, FREQUENCY, MEAN, COS_AMP, SIN_AMP, ERROR)
  WRITE(*,*) ERROR
  WRITE(*,*) MEAN
  DO I = 1_IK, LIMIT,1_IK
    WRITE(*,*) COS_AMP(I), SIN_AMP(I)
  END DO
  WRITE(*,*)
  DEALLOCATE(FREQUENCY)
  DEALLOCATE(COS_AMP)
  DEALLOCATE(SIN_AMP)

END PROGRAM EXAMPLE