! EXAMPLE-09: FREQUENCY CORRECTION
PROGRAM EXAMPLE

  USE SIGNAL

  IMPLICIT NONE

  INTEGER(IK), PARAMETER           :: LENGTH = 2_IK**9_IK   ! INPUT SIGNAL LENGTH
  INTEGER(IK)                      :: FLAG                  ! COMPLEX FLAG (0/1)
  INTEGER(IK)                      :: METHOD                ! FREQUENCY ESTIMATION METHOD
  INTEGER(IK)                      :: MODE                  ! DECOMPOSITION MODE
  INTEGER(IK)                      :: ORDER                 ! COSINE WINDOW ORDER
  REAL(RK), DIMENSION(LENGTH)      :: WINDOW                ! COSINE WINDOW DATA
  REAL(RK)                         :: TOTAL                 ! SUM OF WINDOW ELEMENTS
  REAL(RK), DIMENSION(LENGTH)      :: SIGNAL_R, SIGNAL_I    ! SIGNAL REAL AND COMPLEX PARTS
  REAL(RK), DIMENSION(2_IK*LENGTH) :: SIGNAL                ! INPUT SIGNAL, [..., SR_I, SI_I, ...]
  INTEGER(IK), PARAMETER           :: LOOP = 4_IK           ! NUMBER OF HARMONICS
  REAL(RK), DIMENSION(LOOP)        :: FREQUENCY             ! FREQUENCIES
  REAL(RK), DIMENSION(LOOP)        :: COS_AMP               ! COS-AMPLITUDES
  REAL(RK), DIMENSION(LOOP)        :: SIN_AMP               ! SIN-AMPLITUDES

  REAL(RK), PARAMETER              :: F(4) = [1._RK*0.123456789_RK,2._RK*0.123456789_RK,3._RK*0.123456789_RK,4._RK*0.123456789_RK]
  REAL(RK), PARAMETER              :: A(4) = [1.0_RK,1.0E-1_RK,1.E-3_RK,0.0_RK]
  REAL(RK), PARAMETER              :: B(4) = [1.0E-1_RK,5.0E-2_RK,0.0_RK,1.E-4_RK]

  INTEGER(IK)                      :: I

  ! SET COMPLEX FLAG (0/1 FOR REAL/COMPLEX SIGNAL)
  FLAG = 1_IK

  ! SET SIGNAL REAL AND IMAGINARY PARTS
  SIGNAL_R = 1.0_RK
  SIGNAL_I = 0.0_RK
  DO I = 1_IK, LENGTH, 1_IK
    SIGNAL_R(I) = &
      A(1)*COS(TWO_PI*F(1)*REAL(I, RK)) + B(1)*SIN(TWO_PI*F(1)*REAL(I, RK)) + &
      A(2)*COS(TWO_PI*F(2)*REAL(I, RK)) + B(2)*SIN(TWO_PI*F(2)*REAL(I, RK)) + &
      A(3)*COS(TWO_PI*F(3)*REAL(I, RK)) + B(3)*SIN(TWO_PI*F(3)*REAL(I, RK)) + &
      A(4)*COS(TWO_PI*F(4)*REAL(I, RK)) + B(4)*SIN(TWO_PI*F(4)*REAL(I, RK))
    SIGNAL_I(I) = &
      B(1)*COS(TWO_PI*F(1)*REAL(I, RK)) - A(1)*SIN(TWO_PI*F(1)*REAL(I, RK)) + &
      B(2)*COS(TWO_PI*F(2)*REAL(I, RK)) - A(2)*SIN(TWO_PI*F(2)*REAL(I, RK)) + &
      B(3)*COS(TWO_PI*F(3)*REAL(I, RK)) - A(3)*SIN(TWO_PI*F(3)*REAL(I, RK)) + &
      B(4)*COS(TWO_PI*F(4)*REAL(I, RK)) - A(4)*SIN(TWO_PI*F(4)*REAL(I, RK))
  END DO

  ! FORMAT TEST SIGNAL
  SIGNAL = 0.0_RK
  IF(FLAG == 0_IK) THEN
    CALL CONVERT_(LENGTH, SIGNAL_R, SIGNAL)
  ELSE
    CALL CONVERT_(LENGTH, SIGNAL_R, SIGNAL_I, SIGNAL)
  END IF

  ! SET WINDOW AND WINDOW SUM
  ORDER = 1_IK
  CALL WINDOW_(LENGTH, ORDER, WINDOW)
  TOTAL = SUM(WINDOW)

  ! PRINT INPUT SIGNAL PARAMETERS
  WRITE(*, *) "INPUT"
  WRITE(*, *) F(1), A(1), B(1)
  WRITE(*, *) F(2), A(2), B(2)
  WRITE(*, *) F(3), A(3), B(3)
  WRITE(*, *) F(4), A(4), B(4)
  WRITE(*, *)

  ! ESTIMATE FREQUENCIES AND AMPLITUDES USING MAXIMUM BIN AND SUBTRACTION
  ! FREQUENCIES ARE ESTIMATED FROM LARGEST BIN
  WRITE(*, *) "DECOMPOSITION (SUBTRACTION)"
  METHOD = FREQUENCY_PARABOLA
  MODE = DECOMPOSITION_SUBTRACT
  FREQUENCY = 0.0_RK
  COS_AMP = 0.0_RK
  SIN_AMP = 0.0_RK
  CALL DECOMPOSITION_(FLAG, METHOD, MODE, LENGTH, LENGTH, TOTAL, WINDOW, SIGNAL, LOOP, FREQUENCY, COS_AMP, SIN_AMP)
  DO I = 1_IK, LOOP, 1_IK
    WRITE(*, *) FREQUENCY(I), COS_AMP(I), SIN_AMP(I)
  END DO
  WRITE(*, *)

  ! FREQUENCY CORRECTION
  ! THIS PROCEDURE CAN BE APPLIED TO FIND CORRECTIONS TO ESTIMATED FREQUENCIES AND AMPLITUDES
  ! FIRST, SIGNAL (COMPLETE) DECOMPOSTITION IS PERFORMED AND PARAMETER ESTIMATIONS ARE COMPUTED
  ! NEXT, BASED ON ESTIMATED PARAMETERS MODEL SIGNAL IS GENERATED AND (COMPLETE) DECOMPOSITION IS PERFORMED
  ! AND CORRECTIONS ARE COMMPUTED
  BLOCK
    REAL(RK), DIMENSION(LOOP) :: C_FREQUENCY
    REAL(RK), DIMENSION(LOOP) :: C_COS_AMP
    REAL(RK), DIMENSION(LOOP) :: C_SIN_AMP
    C_FREQUENCY = FREQUENCY
    C_COS_AMP = COS_AMP
    C_SIN_AMP = SIN_AMP
    CALL FREQUENCY_CORRECTION_(FLAG, METHOD, MODE, LENGTH, TOTAL, WINDOW, LOOP, C_FREQUENCY, C_COS_AMP, C_SIN_AMP)
    WRITE(*, *) "ORIGINAL ERRORS"
    WRITE(*, *) "FRE", ABS(FREQUENCY-F)
    WRITE(*, *) "COS", ABS(COS_AMP-A)
    WRITE(*, *) "SIN", ABS(SIN_AMP-B)
    WRITE(*, *)
    WRITE(*, *) "CORRECTED ERRORS"
    WRITE(*, *) "FRE", ABS(C_FREQUENCY-F)
    WRITE(*, *) "COS", ABS(C_COS_AMP-A)
    WRITE(*, *) "SIN", ABS(C_SIN_AMP-B)
  END BLOCK
  WRITE(*, *)

END PROGRAM EXAMPLE